"""Explicit environment contract for trusted local scan subprocesses."""
from collections.abc import Mapping


RUNTIME_KEYS = frozenset({
    "PATH", "HOME", "USER", "LOGNAME", "LANG", "LC_ALL", "LC_CTYPE", "TZ",
    "TMPDIR", "TMP", "TEMP", "SYSTEMROOT", "WINDIR", "USERPROFILE", "APPDATA",
    "LOCALAPPDATA", "PYTHONPATH", "PYTHONUNBUFFERED", "PYTHONDONTWRITEBYTECODE",
    "SSL_CERT_FILE", "SSL_CERT_DIR", "REQUESTS_CA_BUNDLE", "CURL_CA_BUNDLE",
    "HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "NO_PROXY",
    "http_proxy", "https_proxy", "all_proxy", "no_proxy",
    "CRIS_SME_DATASET_SOURCE_TYPE", "CRIS_SME_DATASET_USE", "CRIS_SME_ENABLE_NARRATOR",
    "CRIS_SME_NARRATOR_PROVIDER", "CRIS_SME_NARRATOR_MODEL", "CRIS_SME_NARRATOR_MAX_TOKENS",
    "CRIS_SME_NARRATOR_TEMPERATURE", "CRIS_SME_NARRATOR_TIMEOUT_SECONDS",
})
AWS_KEYS = frozenset({
    "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN", "AWS_PROFILE",
    "AWS_DEFAULT_PROFILE", "AWS_REGION", "AWS_DEFAULT_REGION", "AWS_CONFIG_FILE",
    "AWS_SHARED_CREDENTIALS_FILE", "AWS_CA_BUNDLE", "AWS_ROLE_ARN", "AWS_ROLE_SESSION_NAME",
    "AWS_WEB_IDENTITY_TOKEN_FILE", "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI",
    "AWS_CONTAINER_CREDENTIALS_FULL_URI", "AWS_CONTAINER_AUTHORIZATION_TOKEN",
    "AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE", "AWS_EC2_METADATA_DISABLED",
    "AWS_METADATA_SERVICE_TIMEOUT", "AWS_METADATA_SERVICE_NUM_ATTEMPTS",
    "AWS_RETRY_MODE", "AWS_MAX_ATTEMPTS", "AWS_SDK_LOAD_CONFIG",
    "CRIS_SME_AWS_REGIONS", "CRIS_SME_AWS_SECTOR",
})
AZURE_KEYS = frozenset({
    "AZURE_CONFIG_DIR", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_TENANT_ID",
    "AZURE_CLIENT_CERTIFICATE_PATH", "AZURE_CLIENT_CERTIFICATE_PASSWORD",
    "AZURE_CLIENT_SEND_CERTIFICATE_CHAIN", "AZURE_AUTHORITY_HOST", "AZURE_FEDERATED_TOKEN_FILE",
    "IDENTITY_ENDPOINT", "IDENTITY_HEADER", "IMDS_ENDPOINT", "MSI_ENDPOINT", "MSI_SECRET",
    "AZURE_TOKEN_CREDENTIALS", "CRIS_SME_AZURE_SECTOR", "CRIS_SME_AZURE_RESOURCE_GROUP_SCOPE",
})


def scan_environment(source: Mapping[str, str], provider: str) -> dict[str, str]:
    if provider not in {"aws", "azure"}:
        raise ValueError("Unsupported scan provider")
    allowed = RUNTIME_KEYS | (AWS_KEYS if provider == "aws" else AZURE_KEYS)
    result = {key: value for key, value in source.items() if key in allowed}
    if source.get("CRIS_SME_ENABLE_NARRATOR", "").strip().lower() in {"1", "true", "yes", "on"}:
        if "ANTHROPIC_API_KEY" in source:
            result["ANTHROPIC_API_KEY"] = source["ANTHROPIC_API_KEY"]
    return result
