# Core finding model representing a single governance or compliance observation.
from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_validator


class FindingSeverity(str, Enum):
    """Supported severity levels for deterministic risk scoring."""

    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"


class FindingCategory(str, Enum):
    """Supported control categories for CRIS-SME findings."""

    IAM = "IAM"
    NETWORK = "Network"
    DATA = "Data"
    MONITORING = "Monitoring/Logging"
    COMPUTE = "Compute/Workloads"
    GOVERNANCE = "Cost/Governance Hygiene"


class RemediationCostTier(str, Enum):
    """Supported cost tiers for implementing a remediation in SME contexts."""

    FREE = "free"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class Finding(BaseModel):
    """Normalized finding generated by a collector or control evaluation step."""

    control_id: str = Field(..., min_length=3, description="Unique control identifier.")
    title: str = Field(..., min_length=5, description="Human-readable finding title.")
    category: FindingCategory = Field(..., description="Control category for aggregation.")
    severity: FindingSeverity = Field(..., description="Deterministic severity label.")
    evidence: list[str] = Field(
        default_factory=list,
        description="Evidence statements supporting the finding.",
    )
    resource_scope: str = Field(
        ...,
        min_length=3,
        description="Cloud resource, account, subscription, or logical scope affected.",
    )
    is_compliant: bool = Field(
        ...,
        description="Whether the evaluated control is compliant at scan time.",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence in the finding based on data quality and check coverage.",
    )
    exposure: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Exposure level from isolated to internet-facing.",
    )
    data_sensitivity: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Sensitivity of the impacted data or business process.",
    )
    remediation_effort: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Estimated effort required to remediate the finding.",
    )
    remediation_summary: str = Field(
        default="",
        description="Short plain-language remediation guidance for the finding.",
    )
    remediation_cost_tier: RemediationCostTier | None = Field(
        default=None,
        description="Approximate SME-oriented cost tier for remediation.",
    )
    mapping: list[str] = Field(
        default_factory=list,
        description="Compliance or governance mappings related to the finding.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional structured context for downstream analysis.",
    )

    @field_validator("evidence", "mapping")
    @classmethod
    def strip_empty_items(cls, values: list[str]) -> list[str]:
        """Normalize list fields by trimming whitespace and dropping empty values."""
        return [value.strip() for value in values if value.strip()]

    @property
    def is_risk(self) -> bool:
        """Return True when the finding represents a non-compliant state."""
        return not self.is_compliant
